---
title: "Schedule"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Week | Day | Date                    | Topic                                                                                                           | Guest Speaker                                        | Readings                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Due                                                                       |
|------|-----|-------------------------|-----------------------------------------------------------------------------------------------------------------|------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------|
| 1    | TH  | 2-Sep                   | Introduction & Course Expectations                                                                              |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 2    | T   | 7-Sep                   | Fundamentals of Science and How We Study the Brain                                                              |                                                      | CH.1 JHANGIANI et al. CH.2 JHANGIANI et al.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | September 10th is last day to drop a course without a "W" grade           |
| 2    | TH  | 9-Sep                   | Research Ethics                                                                                                 |                                                      | CH.3 JHANGIANI et al.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |   Team Charter Due by Friday, September 10th                              |
| 3    | T   | 14-Sep                  | Sources of Information                                                                                          | Laura Mullen (Rutgers Behavioral Sciences Librarian) |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 3    | TH  | 16-Sep                  | Ethics Training: CITI TRAINING                                                                                  |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Topic Approval Due by Friday September 17th                               |
| 4    | T   | 21-Sep                  | Open Science/Replication                                                                                        |                                                      | - Simmons, J. P., Nelson, L. D., & Simonsohn, U. (2011). False-Positive Psychology: Undisclosed Flexibility in Data Collection and Analysis Allows Presenting Anything as Significant. Psychological Science, 22(11), 1359–1366. https://doi.org/10.1177/0956797611417632  (here is great youtube video that summarizes the article: https://www.youtube.com/watch?v=bf3GqyBRgzY&t=562s)  - Nosek, B. A., Ebersole, C. R., DeHaven, A. C., & Mellor, D. T. (2018). The preregistration revolution. Proceedings of the National Academy of Sciences, 115(11), 2600. https://doi.org/10.1073/pnas.1708274114                                                                                                       |                                                                           |
| 4    | Th  | 23-Sep                  | Open Science/Replication                                                                                        |                                                      | - Brandt, M. J., IJzerman, H., Dijksterhuis, A., Farach, F. J., Geller, J., Giner-Sorolla, R., Grange, J. A., Perugini, M., Spies, J. R., & van ’t Veer, A. (2014). The Replication Recipe: What makes for a convincing replication? Journal of Experimental Social Psychology, 50, 217–224 https://doi.org/10.1016/j.jesp.2013.10.005l - Frank, M. C., & Saxe, R. (2012). Teaching Replication.Perspectives on Psychological Science,7(6),600–604.https://doi.org/10.1177/1745691612460686                                                                                                                                                                                                                      | 1 page summary, CITI training, and IRB forms due by Friday September 24th |
| 5    | T   | 28-Sep                  | Psychological Measurement                                                                                       |                                                      | CH.4 JHANGIANI et al.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                           |
| 5    | Th  | 30-Sep                  | Experiment Basics                                                                                               |                                                      | CH.5 JHANGIANI et al.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                                                           |
| 6    | T   | 5-Oct                   | Exploring Cognition Through the Eyes: Reading and Eye-tracking                                                  |                                                      | - Rayner, K., Schotter, E. R., Masson, M. E. J., Potter, M. C., & Treiman, R. (2016). So Much to Read, So Little Time: How Do We Read, and Can Speed Reading Help? Psychological Science in the Public Interest, 17(1), 4–34 https://doi.org/10.1177/1529100615623267 - Slattery, T. J. Eye movements: From psycholinguistics to font design. In Digital Fonts and Reading (eds Dyson, M. C. & Yuen, C. Y.), 54–78 (World Scientific, 2016).                                                                                                                                                                                                                                                                     |                                                                           |
| 6    | TH  | 7-Oct                   | Exploring Cognition Through the Eyes: Pupillometry                                                              | Sarah Colby (University of Iowa): Pupillometry       | - Torres A and Hout M (2019) Pupils: A Window Into the Mind. Front. Young Minds. 7:3. doi: 10.3389/frym.2019.00003 - Laeng, B., Sirois, S., & Gredebäck, G. (2012). Pupillometry: A Window to the Preconscious? Perspectives on Psychological Science, 7(1), 18–27. https://doi.org/10.1177/1745691611427305                                                                                                                                                                                                                                                                                                                                                                                                     | Preregistration due by Friday October 8th                                 |
| 7    | T   | 12-Oct                  | Exploring Cognition Through the Eyes: Eye-tracking and Pupillometry (RuCCS eye-tracking lab)                    |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 7    | TH  | 14-Oct                  | Exploring Cognition Through the Brain: EEG                                                                      | McCall Syrett (Villanova University): EEG            | - Allopenna, P. D. , Magnuson, J. S. , & Tanenhaus, M. K. (1998). Tracking the time course of spoken word recognition using eye movements: Evidence for continuous mapping models. Journal of Memory and Language, 38, 419–439.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 8    | T   | 19-Oct                  | Exploring Cognition Through the Brain : EEG                                                                     | Ryan Rhodes (Rutgers University): EEG                | - Etienne, A., Laroia, T., Weigle, H., Afelin, A., Kelly, S. K., Krishnan, A., & Grover, P. (2020). Novel Electrodes for Reliable EEG Recordings on Coarse and Curly Hair. BioRxiv, 2020.02.26.965202. https://doi.org/10.1101/2020.02.26.965202                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                                           |
| 8    | TH  | 21-Oct                  | Exploring Cognition Through the Brain: EEG                                                                      |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 9    | T   | 26-Oct                  | Understanding Cognition Through the Brain: fMRI                                                                 | Melissa Thye (University of Edinburgh): fMRI/sEEG    | - Racine, E., Bar-Ilan, O., & Illes, J. (2005). FMRI in the public eye. Nature Reviews Neuroscience, 6(2), 159–164. https://doi.org/10.1038/nrn1609 - Turner, R. (2016). Uses, misuses, new uses and fundamental limitations of magnetic resonance imaging in cognitive science. Philosophical Transactions of the Royal Society B: Biological Sciences, 371(1705). https://doi.org/10.1098/rstb.2015.0349- Amanamba U., Sojka A., Harris S., Bucknam M.,& Hegdé. J. (2020) A Window Into Your Brain: How fMRI Helps Us Understand What Is Going on Inside Our Heads. Front. Young Minds. 8:484603. doi: 10.3389/frym.2020.484603                                                                                |                                                                           |
| 9    | TH  | 28-Oct                  | Understanding Cognition Through the Brain: fMRI (The Center for Advanced Human Brain Imaging Research (CAHBIR)) |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 10   | T   | 2-Nov                   | Exploring Cognition Through the Web                                                                             |                                                      | - Crump, McDonnell, Gureckis (2013). Evaluating Amazon's Mechanical Turk as a Tool for Experimental Behavioral Research - Bridges, D., Pitiot, A., MacAskill, M. R., & Peirce, J. W. (2020). The timing mega-study: Comparing a range of experiment generators, both lab-based and online. PeerJ, 8, e9414. https://doi.org/10.7717/peerj.9414- - Grootswagers, T. A primer on running human behavioral experiments online. Behav Res 52, 2283–2286 (2020).https://doi.org/10.3758/s13428-020-01395-3 - Gagné, N., & Franzen, L., Ph.D. (2021, August 30). How to run behavioural experiments online: best practice suggestions for cognitive psychology and neuroscience. https://doi.org/10.31234/osf.io/nt67j |                                                                           |
| 10   | TH  | 4-Nov                   | No Class - Psychonomics No Calss                                                                                |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 11   | T   | 9-Nov                   | Introduction to Python/PsychoPy and Pavlovia                                                                    |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 11   | TH  | 11-Nov                  |                                                                                                                 | Lucia Cherep (Univeristy of Arizona): VR             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 12   | T   | 16-Nov                  | Introduction to Python/PsychoPy and Pavlovia & Normalizing Errors                                               |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 12   | TH  | 18-Nov                  | Programming Experiments                                                                                         |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 13   | T   | 23-Nov                  | Programming Experiments                                                                                         |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 13   | TH  | 25-Nov                  | Thanksgiving Break (No Class)                                                                                   |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 14   | T   | 30-Nov                  | Data Collection                                                                                                 |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Programmed Experiment Due by November 30th.                               |
| 14   | TH  | 2-Dec                   | Data Collection                                                                                                 |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 15   | T   | 7-Dec                   | Data Analysis                                                                                                   |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 15   | TH  | 9-Dec                   | Data Analysis                                                                                                   |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Methods and Data Analysis Write-Up Due by December 10th                   |
| 16   | T   | 14-Dec                  | Class Presentations                                                                                             |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
| 16   | TH  | 16-Dec                  | Class Presentations                                                                                             |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                                                           |
|      |     | 12/20/2021 - 12/23/2021 | FINAL EXAMS (DECEMBER 20th-DECEMBER 23rd)                                                                       |                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Paper Due by December 23rd                                                |
